brbox: raspi2-update wip

diff --git a/sources/scripts/raspi2/update/raspi2-update b/sources/scripts/raspi2/update/raspi2-update
--- a/sources/scripts/raspi2/update/raspi2-update
+++ b/sources/scripts/raspi2/update/raspi2-update
@@ -3,8 +3,9 @@ MKFSTOOL=/usr/sbin/mkfs.ext3
 BRDSKMGR_TOOL=/usr/sbin/brdskmgr
 ONE_BRBOX_NAME=brbox1 #name of the first brbox system
 TWO_BRBOX_NAME=brbox2 #name of the second brbox system
-ONE_BRBOX_PART=sda2 #partition
-TWO_BRBOX_PART=sda3 #partition
+ONE_BRBOX_PART=mmcblk0p2 #root1 partition
+TWO_BRBOX_PART=mmcblk0p3 #root2 partition
+BOOT_BRBOX_PART=mmcblk0p1
 ROOT1_LABEL=ROOT1   #linux-1
 ROOT2_LABEL=ROOT2   #linux-2
 GRUBCFG_FILE_PATH=/boot/grub/grub.cfg
@@ -17,7 +18,7 @@ MULTI_MK_NOK="multi_mk_nok"
 SINGL_BINARY="singl_binary"
 
 BRBOX_PROJ="BrBoxProj"    #complete project including all sub-modules
-BRBOX_ROOT="BrBoxRoot"    #rootfs
+BRBOX_ROOT="BrBoxRtRp2"    #rootfs
 BRBOX_STTNG="BrBoxSttng"  #settings partition
 BRBOX_USRDAT="BrBoxUsrDt" #user-data partition 
 
@@ -101,9 +102,11 @@ ProcessUpdate() #$1=input-update-file $2-output-file(if-applicable)
 		printf "Checking file type............ "
 		IMGTYPE=$(GetImageType $1)
 		[ $? != "0" ] && { echo "[FAIL]" ; return 1; }
-		echo "$IMGTYPE.... [OK]"
+		#echo "$IMGTYPE.... [OK]"
 		ProcessImageType $1 $IMGTYPE $2
-		return $?
+		[ $? != "0" ] && { echo "[FAIL]" ; return 1; }
+		echo "$IMGTYPE.... [OK]"
+		return 0
 	elif [ "$FILE_TYPE" = "$MULTI_MK_OK" ]; then
 		TOTAL_SUB_IMAGES=$(grep "total-sub-images=" $TMPFILE)
 		TOTAL_SUB_IMAGES=$(echo $TOTAL_SUB_IMAGES | sed 's/total-sub-images=//' )
@@ -131,6 +134,7 @@ done
 [ ! -f  "$UPDATE_FILE"  ] && { echo "Error: Update file not found!!!"; return 1; }
 TMP_ROOTFSFILE=$(mktemp) #creates an emptyfile which will be filled by ProcessUpdate as rootfs.tar.xz
 ProcessUpdate $UPDATE_FILE $TMP_ROOTFSFILE
+[ $? != "0" ] && { echo "Error: Invalid filetype" ; return 1; }
 #TODO:mkimage file integrity 
 file $TMP_ROOTFSFILE | grep "XZ compressed data" > /dev/null
 [ $? != 0 ] && { echo "Error: Update file must be xz compressed!!!"; rm -rf $TMP_ROOTFSFILE; return 1; }
@@ -141,7 +145,7 @@ CUR_BOOT=$($BRDSKMGR_TOOL -c)
 [ $? != 0 ] && { echo "Error: Unable to read current system!!!"; rm -rf $TMP_ROOTFSFILE; return 1; }
 
 #during fmw update remount the current rootfs and writable(coz grub.cfg needs to be modified)
-mount -o remount,rw / 1>/dev/null 2>/dev/null
+#mount -o remount,rw / 1>/dev/null 2>/dev/null
 
 #if first system is booted, then update second system
 if [ "$CUR_BOOT" = "$ONE_BRBOX_NAME" ]; then
@@ -153,12 +157,12 @@ elif [ "$CUR_BOOT" = "$TWO_BRBOX_NAME" ]; then
 	#before updating brbox1, update my(brbox2) grub.cfg's "set default" flag to 1 so that
 	#mbr-grub can call my(brbox2) grub.cfg incase of corrupt brbox1
 	#this will ensure that brbox2 will be booted incase of corrupt brbox1
-	sed -i "s|set default=.*|set default=1|" $GRUBCFG_FILE_PATH
+#	sed -i "s|set default=.*|set default=1|" $GRUBCFG_FILE_PATH
 else
 	#booted system is neither brbox1 nor brbox2
 	echo "Error: Unknown boot system!!!" 
 	rm -rf $TMP_ROOTFSFILE;
-	mount -o remount,ro / 1>/dev/null 2>/dev/null
+	#mount -o remount,ro / 1>/dev/null 2>/dev/null
 	return 1
 fi
 #TODO: set a flag in /mnt/setting to know that fmw-update has begun
@@ -167,7 +171,7 @@ $MKFSTOOL -F -L $BRBOX_LABEL $BRBOX_PARTITION 1>/dev/null 2>/dev/null
 if [ $? != "0" ]; then #unable format ext3 filesystem
 	echo "Error: Unable to format ext3 filesystem!!!"
 	rm -rf $TMP_ROOTFSFILE;
-	mount -o remount,ro / 1>/dev/null 2>/dev/null
+	#mount -o remount,ro / 1>/dev/null 2>/dev/null
 	return 1
 fi
 echo "[OK]"
@@ -176,7 +180,7 @@ TEMP_MOUNT_POINT=$(mktemp -d)
 if [ $? != "0" ]; then #unable to create temp mount directory
 	echo "Error: Unable to create temp directory!!!"
 	rm -rf $TMP_ROOTFSFILE;
-	mount -o remount,ro / 1>/dev/null 2>/dev/null
+	#mount -o remount,ro / 1>/dev/null 2>/dev/null
 	return 1
 fi
 mount $BRBOX_PARTITION $TEMP_MOUNT_POINT
@@ -184,7 +188,7 @@ if [ $? != "0" ]; then #unable mount device, filesystem might be corrupt
 	echo "Error: Unable to mount $BRBOX_PARTITION to $TEMP_MOUNT_POINT!!!"
 	rm -r $TEMP_MOUNT_POINT
 	rm -rf $TMP_ROOTFSFILE
-	mount -o remount,ro / 1>/dev/null 2>/dev/null
+	#mount -o remount,ro / 1>/dev/null 2>/dev/null
 	return 1
 fi
 printf "Copying new filesystem to $BRBOX_PARTITION ........ "
@@ -194,21 +198,59 @@ if [ $? != "0" ]; then #unable to copy files
 	umount $BRBOX_PARTITION
 	rm -r $TEMP_MOUNT_POINT
 	rm -rf $TMP_ROOTFSFILE
-	mount -o remount,ro / 1>/dev/null 2>/dev/null
+	#mount -o remount,ro / 1>/dev/null 2>/dev/null
 	return 1
 fi
 echo "[OK]"
 
-cp $GRUBCFG_FILE_PATH $TEMP_MOUNT_POINT/$GRUBCFG_FILE_PATH
-sync
+sync #let new rootfs files to be written to corresponding partition
+
+#copy zImage to /boot partition
+TEMP_BOOT_MOUNT_POINT=$(mktemp -d)
+if [ $? != "0" ]; then #unable to create temp mount directory
+	echo "Error: Unable to create temp directory for boot mount!!!"
+	umount $BRBOX_PARTITION
+	rm -r $TEMP_MOUNT_POINT
+	rm -rf $TMP_ROOTFSFILE
+	return 1
+fi
+
+BRBOX_BOOT_PARTITION=/dev/$BOOT_BRBOX_PART
+mount $BRBOX_BOOT_PARTITION $TEMP_BOOT_MOUNT_POINT
+if [ $? != "0" ]; then #unable mount device, boot-filesystem might be corrupt
+	echo "Error: Unable to mount $BRBOX_BOOT_PARTITION to $TEMP_BOOT_MOUNT_POINT!!!"
+	umount $BRBOX_PARTITION
+	rm -r $TEMP_MOUNT_POINT
+	rm -rf $TMP_ROOTFSFILE
+	rm -rf $TEMP_BOOT_MOUNT_POINT
+	return 1
+fi
+printf "Copying zImage to $BRBOX_BOOT_PARTITION ........ "
+if [ "$CUR_BOOT" = "$ONE_BRBOX_NAME" ]; then
+	cp $TEMP_MOUNT_POINT/zImage $TEMP_BOOT_MOUNT_POINT/zImage2
+elif [ "$CUR_BOOT" = "$TWO_BRBOX_NAME" ]; then
+	cp $TEMP_MOUNT_POINT/zImage $TEMP_BOOT_MOUNT_POINT/
+else
+	echo "Error: Unknown boot system!!!" 
+	umount $BRBOX_PARTITION
+	rm -r $TEMP_MOUNT_POINT
+	rm -rf $TMP_ROOTFSFILE
+	umount $BRBOX_BOOT_PARTITION
+	rm -rf $TEMP_BOOT_MOUNT_POINT
+	return 1
+fi
+sync #let zImage be copied to boot partition
 umount $BRBOX_PARTITION
+umount $BRBOX_BOOT_PARTITION
 rm -r $TEMP_MOUNT_POINT
 rm -rf $TMP_ROOTFSFILE
+rm -rf $TEMP_BOOT_MOUNT_POINT
+
 $BRDSKMGR_TOOL -f #flip the boot-marker flag, so that next time updated system will boot
 [ $? != 0 ] && { echo "Error: Unable to flip boot-marker flag!!!"; return 1; }
 #TODO: reset a flag in /mnt/setting to know that fmw-update has has completed successfully(this will inform the system that fmw update was success).
 
-mount -o remount,ro / 1>/dev/null 2>/dev/null
+#mount -o remount,ro / 1>/dev/null 2>/dev/null
 echo "FinalResult ................................ [OK]"
 return 0
 
