brbox: raspi-2 update script calls find-devtype detected device to validate mk-update image

diff --git a/sources/scripts/raspi2/update/raspi2-update b/sources/scripts/raspi2/update/raspi2-update
--- a/sources/scripts/raspi2/update/raspi2-update
+++ b/sources/scripts/raspi2/update/raspi2-update
@@ -22,8 +22,15 @@ BRBOX_STTNG="BrBoxSttng"  #settings partition
 BRBOX_USRDAT="BrBoxUsrDt" #user-data partition 
 BRBOX_ROOT_RP1="BrBoxRtRp1"    #rootfs
 BRBOX_ROOT_RP2="BrBoxRtRp2"    #rootfs
-BOARD_TYPE_RP1="raspi1"
-BOARD_TYPE_RP2="raspi2"
+#BOARD_TYPE_RP1="raspi1"
+#BOARD_TYPE_RP2="raspi2"
+BD_TYP_RASPI_A="RASPI_A"
+BD_TYP_RASPI_APLUS="RASPI_APLUS"
+BD_TYP_RASPI_B="RASPI_B"
+BD_TYP_RASPI_BPLUS="RASPI_BPLUS"
+BD_TYP_RASPI_B2="RASPI_B2"
+
+DEV_TYPE_FILE=/tmp/BrBoxDevType.txt
 
 GLOBAL_VAR_TOTAL_FILES=0
 ###############################################################################
@@ -85,18 +92,20 @@ GetImageType() #$-input-file
 ###############################################################################
 ProcessImageType() #$1-inputfile $2=IMGTYPE $3=outputfile
 {
-	#BRBOX_PROJ="BrBoxProj"    #complete project including all sub-modules
-	#BRBOX_ROOT="BrBoxRoot"    #rootfs
-	#BRBOX_STTNG="BrBoxSttng"  #settings partition
-	#BRBOX_USRDAT="BrBoxUsrDt" #user-data partition 
+	BOARD_TYPE=$(cat $DEV_TYPE_FILE)
 
-	BOARD_TYPE=$($BRDSKMGR_TOOL -t)
-	[ $? != 0 ] && { echo "Error: Unable to read board type!!!"; return 1; }
+	#BOARD_TYPE=$($BRDSKMGR_TOOL -t)
+	#[ $? != 0 ] && { echo "Error: Unable to read board type!!!"; return 1; }
 
 	BRBOX_ROOT="unknown"
+	#[ "$BOARD_TYPE" = "$BOARD_TYPE_RP1" ]  && BRBOX_ROOT=$BRBOX_ROOT_RP1
+	#[ "$BOARD_TYPE" = "$BOARD_TYPE_RP2" ]  && BRBOX_ROOT=$BRBOX_ROOT_RP2
 
-	[ "$BOARD_TYPE" = "$BOARD_TYPE_RP1" ]  && BRBOX_ROOT=$BRBOX_ROOT_RP1
-	[ "$BOARD_TYPE" = "$BOARD_TYPE_RP2" ]  && BRBOX_ROOT=$BRBOX_ROOT_RP2
+	[ "$BOARD_TYPE" = "$BD_TYP_RASPI_A"     ]  && BRBOX_ROOT=$BRBOX_ROOT_RP1
+	[ "$BOARD_TYPE" = "$BD_TYP_RASPI_APLUS" ]  && BRBOX_ROOT=$BRBOX_ROOT_RP1
+	[ "$BOARD_TYPE" = "$BD_TYP_RASPI_B"     ]  && BRBOX_ROOT=$BRBOX_ROOT_RP1
+	[ "$BOARD_TYPE" = "$BD_TYP_RASPI_BPLUS" ]  && BRBOX_ROOT=$BRBOX_ROOT_RP1
+	[ "$BOARD_TYPE" = "$BD_TYP_RASPI_B2"    ]  && BRBOX_ROOT=$BRBOX_ROOT_RP2
 
 	if [ "$2" = "$BRBOX_ROOT" ]; then
 		dd if=$1 bs=64 skip=1 of=$3 1>/dev/null 2>/dev/null #just strip 64byte mkheader and create rootfs.tar.xz
