brbox: working flip mechanism based on rootfs.tar update package

diff --git a/disk_skeleton/usr/sbin/update b/disk_skeleton/usr/sbin/update
--- a/disk_skeleton/usr/sbin/update
+++ b/disk_skeleton/usr/sbin/update
@@ -1,9 +1,14 @@
 #!/bin/sh
+MKFSTOOL=/usr/sbin/mkfs.ext3
 BRDSKMGR_TOOL=/usr/sbin/brdskmgr
 ONE_BRBOX_NAME=brbox1 #name of the first brbox system
 TWO_BRBOX_NAME=brbox2 #name of the second brbox system
 ONE_BRBOX_PART=sda2 #partition
 TWO_BRBOX_PART=sda3 #partition
+ROOT1_LABEL=ROOT1   #linux-1
+ROOT2_LABEL=ROOT2   #linux-2
+GRUBCFG_FILE_PATH=/boot/grub/grub.cfg
+
 
 while getopts u: f
 do
@@ -22,17 +27,45 @@ CUR_BOOT=$($BRDSKMGR_TOOL -c)
 #if first system is booted, then update second system
 if [ "$CUR_BOOT" = "$ONE_BRBOX_NAME" ]; then
 	BRBOX_PARTITION=/dev/$TWO_BRBOX_PART
+	BRBOX_LABEL=$ROOT2_LABEL
 elif [ "$CUR_BOOT" = "$TWO_BRBOX_NAME" ]; then
 	BRBOX_PARTITION=/dev/$ONE_BRBOX_PART
+	BRBOX_LABEL=$ROOT1_LABEL
 else
 	#booted system is neither brbox1 nor brbox2
 	echo "Error: Unknown boot system!!!"; return 1;
 	return 1
 fi
 
-dd if=$UPDATE_FILE of=$BRBOX_PARTITION bs=1M 1>/dev/null 2>/dev/null
-[ $? != 0 ] && { echo "Error: Unable to write update file to $BRBOX_PARTITION!!!"; return 1; }
+$MKFSTOOL -F -L $BRBOX_LABEL $BRBOX_PARTITION 1>/dev/null 2>/dev/null
+if [ $? != "0" ]; then #unable format ext3 filesystem
+	echo "Error: Unable to format ext3 filesystem!!!"; return 1;
+	return 1
+fi
+TEMP_MOUNT_POINT=$(mktemp -d)
+if [ $? != "0" ]; then #unable to create temp mount directory
+	echo "Error: Unable to create temp directory!!!"; return 1;
+	return 1
+fi
+mount $BRBOX_PARTITION $TEMP_MOUNT_POINT
+if [ $? != "0" ]; then #unable mount device, filesystem might be corrupt
+	echo "Error: Unable to mount $BRBOX_PARTITION to $TEMP_MOUNT_POINT!!!"; return 1;
+	rm -r $TEMP_MOUNT_POINT
+	return 1
+fi
+tar -C $TEMP_MOUNT_POINT -xf $UPDATE_FILE
+if [ $? != "0" ]; then #unable to copy files
+	echo "Error: Unable to copy files!!!"; return 1;
+	umount $BRBOX_PARTITION
+	rm -r $TEMP_MOUNT_POINT
+	return 1
+fi
+
+cp $GRUBCFG_FILE_PATH $TEMP_MOUNT_POINT/$GRUBCFG_FILE_PATH
+#TODO: cp /boot/version-num.txt /tmp/tmp.0EBZpt/boot/
 sync
+umount $BRBOX_PARTITION
+rm -r $TEMP_MOUNT_POINT
 $BRDSKMGR_TOOL -f #flip the boot-marker flag, so that next time updated system will boot
 [ $? != 0 ] && { echo "Error: Unable to flip boot-marker flag!!!"; return 1; }
 return 0
